#!/usr/bin/python3

import os, sys, time
from zeroconf import ServiceBrowser, Zeroconf
import requests
from socket import gethostbyname

if((len(sys.argv)<2) or (os.path.isfile(sys.argv[1]) == False)):
    print("Please specify the file to be printed")
    exit(1)
    
servers=[]

class MyListener(object):

    def remove_service(self, zeroconf, type, name):
        print("Service %s removed" % (name,))

    def add_service(self, zeroconf, type, name):
        info = zeroconf.get_service_info(type, name)
        print("Service %s added, service info: %s" % (name, info))
        servers.append(info.server)
        zeroconf.close()

zeroconf = Zeroconf()
listener = MyListener()
browser = ServiceBrowser(zeroconf, "_wirelessprint._tcp.local.", listener)
time.sleep(2)

url = "http://" + servers[0] + "/print" # TODO: Select one of many

files = {'file': open(sys.argv[1], 'rb')}
r = requests.post(url, files=files)
print("Sent")
